### ISSUE TITLE
Contractオブジェクト情報を含んだトランザクションをネットワークに送信できない

### ISSUE THREAD

**Issue by cu39** [a-mitani/mastering-ethereum#56]
まずはEthereumに触れてみる / スマートコントラクトを作成し実行する / 「Contract」アカウントを生成
https://book.ethereum-jp.net/first_use/contract#contractakauntowo

#49 を参考にコントラクト・コードを修正してコンパイルは通ったのですが、コントラクトをネットワークに送信するところでもエラーになりました。

```
> var myContract = contract.new({ from: eth.accounts[0], data: bin})
TypeError: Object has no member 'filter'
	at web3.js:2830:22(7)
	at web3.js:3001:44(108)
	at <eval>:1:29(13)
```

環境は以下のとおりです。

```sh:
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.8.7+commit.e28d00a7.Darwin.appleclang
$ geth version
Geth
Version: 1.10.8-stable
Architecture: amd64
Go Version: go1.16.6
Operating System: darwin
GOPATH=/Users/cu39/go
GOROOT=go
```

**Comment by cu39** [comment]
自己解決しました。つまずいていた原因は2点ありました。

1. `var bin` へ割り当てるバイトコードの先頭に `0x` を付けていなかった。
2. `var abi` へ割り当てるJSON文字列をクォートで囲ってしまっていた。

2は私の凡ミスと言わざるをえませんが、バイトコードの`0x`については何か注意を促す文言があってもよい気がします。

あと、`from`キーに対応するアカウントのアンロックを求められることもありました。チュートリアルをスムーズに進められなかった場合に限られるかもしれませんが、ありうるケースとしてメモしておきます。

```
> var myContract = contract.new({ from: eth.accounts[0], data: bin })
Error: authentication needed: password or unlock
	at web3.js:6357:37(47)
	at web3.js:5091:62(37)
	at web3.js:3021:48(134)
	at <eval>:1:30(13)

> personal.unlockAccount(eth.accounts[0])
```

以上、失礼しました。
